version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    env_file:
      - docker/variables.env
    ports:
      - "15433:5432"
    networks:
      - corpsearch
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: api
    command: ["npm", "run", "start"]
    volumes:
      - ./:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "127.0.0.1:8082:8081"
    env_file:
      - docker/variables.env
    networks:
      - corpsearch
    depends_on:
      - postgres
  chrome:
    image: zenika/alpine-chrome:latest
    command: [chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222", $CHROME_ARGS]
    ports:
      - "9222:9222"
    networks:
      - corpsearch
networks:
  default:
    driver: bridge
  corpsearch:
    driver: bridge
