version: '3'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile-test
    hostname: api
    command: ["npm", "run", "test"]
    volumes:
      - ./:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "23089:8081"
    env_file:
      - docker/variables-test.env
    networks:
      - corpsearch
    depends_on:
      - postgres
  chrome:
    image: zenika/alpine-chrome:latest
    command: [chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - "9222:9222"
    networks:
      - corpsearch
networks:
  default:
    driver: bridge
  corpsearch:
    driver: bridge
